import type { Metadata } from "next";
import { Outfit, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CustomCursor } from "@/components/CustomCursor";
import { MeshBackground } from "@/components/MeshBackground";
import { SmoothScroller } from "@/components/SmoothScroller";

const outfitFont = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${outfitFont.variable} ${geistMono.variable} h-full antialiased text-[16px]`}
    >
      <body className="min-h-full flex flex-col cursor-none text-base overflow-x-clip bg-background" suppressHydrationWarning>
        <SmoothScroller>
          <MeshBackground />
          <CustomCursor />
          {children}
        </SmoothScroller>
      </body>
    </html>
  );
}
